spring:
  application:
    name: spring-oauth2-social-login
  security:
    user:
      name: admin
      password: admin
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
          google:
            client-id:
            client-secret:
            scope: email,profile
server:
  port: 8090